# Generated by Django 5.2.7 on 2025-11-24 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='sno',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
