# Generated by Django 5.2.7 on 2025-11-24 11:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_student_sno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='id',
        ),
        migrations.AlterField(
            model_name='student',
            name='sno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
